name: Cache npm
description: To cache node_modules using npm

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-cache-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cache-npm-
          ${{ runner.os }}-
